Drop Python 3.6 and test with Python 3.9
jupyter/nbconvert pull request #1542
Opened 2021-04-03 13:25 UTC by SylvainCorlay

2021-04-06 11:48 UTC, SylvainCorlay commented
@MSeal what do you think about dropping Python 3.6?

2021-04-06 12:05 UTC, agoose77 commented
@SylvainCorlay are we not forced to drop Python 3.6 support given that [we currently depend upon `traitlets >= 5.0`](https://github.com/jupyter/nbconvert/blob/e49b9a8a220c9f9f87c23764ea7b48eac4707937/setup.py#L219)?

2021-04-22 15:30 UTC, mriedem requested changes
If this is really dropping support for python 3.6 then shouldn't the `python_requires` version in the setup.py be updated to be at least 3.7?

https://github.com/jupyter/nbconvert/blob/9689b2cb0658967e577585825cf8881a81feafa2/setup.py#L191

And if that's the case, the changelog should probably be updated as well right?

https://github.com/jupyter/nbconvert/blob/master/docs/source/changelog.rst

2021-04-22 15:34 UTC, mriedem commented
> If this is really dropping support for python 3.6 then shouldn't the `python_requires` version in the setup.py be updated to be at least 3.7?

I just noticed this in the README:

https://github.com/jupyter/nbconvert#python-requirement

So I guess 3.6 is supported but not all that strongly, and will be dropped in 6.1, so it seems this would be fine if it also triggers a 6.1 release.

2021-04-22 15:36 UTC, agoose77 commented
@mriedem I don't think we can support 3.6 _at all_, because we have a hard dependency on `traitlets=5`. and [`traitlets` has `python_requires>=3.7`](https://github.com/ipython/traitlets/blob/5.0.0/setup.py#L90)

2021-04-22 15:40 UTC, mriedem commented
> However, I don't know what the protocol is when it's a dependency that is enforcing our version constraint. I would assume we drop support for 3.6?

Yeah I'd think so as well. I'm definitely not a regular contributor here, I'm just interested in getting #1470 merged since we need that downstream (we're capping nbconvert<6 as a result which is causing some other issues, i.e. jupyter/jupyter_client/issues/637).

CI has been broken for a few weeks and this PR has been up for about 3 weeks now so just trying to figure out how to proceed with getting CI passing again so things can start flowing for non-maintainers.

2021-04-22 15:41 UTC, mriedem commented
Also, I'm personally fine with dropping support for python 3.6, my -1 is just that I don't think we should probably drop CI testing for 3.6 without also officially dropping support for 3.6 which I think at least means:

- bumping the `python_requires` version in setup.py
- adding a changelog entry
- removing that section of the README about python 3.6
- release a 6.1 version

2021-04-22 15:52 UTC, meeseeksmachine commented
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/current-state-of-nbconvert-drop-support-for-python-3-6/8882/1

2021-04-22 16:03 UTC, agoose77 commented
OK, I have somehow made a mistake here - the current released versions of nbconvert use traitlets 4.x, so we're fine in terms of the release `install_requires`.

2021-04-22 16:07 UTC, mriedem commented
> The PR that introduced traitlets 5 is #1498

Yup and it failed CI but was merged (I can't see settings on the repo but seems failing CI should block a change unless an admin overrides it).

2021-04-22 16:11 UTC, agoose77 commented
> > The PR that introduced traitlets 5 is #1498
> 
> Yup and it failed CI but was merged (I can't see settings on the repo but seems failing CI should block a change unless an admin overrides it).

Right, then I think it's just a case of reflecting the implied changes in the various metadata as you've outlined above :partying_face:

2021-04-22 17:09 UTC, MSeal commented
@SylvainCorlay Sorry I missed the notification on this originally. 3.6 technically has EOL from Python org until 12/21, but if it's desired to drop it given upstream deps dropping 3.6 it's probably fine, as 6.0.x is stable for 3.6 users anyway.

> bumping the python_requires version in setup.py
> adding a changelog entry
> removing that section of the README about python 3.6
> release a 6.1 version

We should probably get a couple other hanging PRs merged, e.g. extension for webpdf export fix, before the 6.1 release step. I've been a bit time constrained so haven't been able to put major effort into helping PRs get patched to a mergable state recently.

2021-04-23 08:26 UTC, closed without merging

2021-06-23 19:51 UTC, meeseeksmachine commented
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/nbconvert-6-1-0-release/9731/1